language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raveekirann/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true raveekirann/docker-react npm run test