#language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raveekirann/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true raveekirann/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker_prod"
  env: "dockerprod-env"
  bucket_name: "elasticbeanstalk-us-east-1-541573570611"
  bucket_path: "docker_prod"
  on:
  branch: master
access_key_id:
  secure: "$AWS_ACCESS_KEY"
secret_access_key:
  secure: "$AWS_SECRET_KEY"
